# Generated by Django 4.2.26 on 2025-11-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updates_on',
            new_name='updated_on',
        ),
    ]
